// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config';
import { env } from 'process';

export default defineConfig({
  datasource: {
    url: env.DATABASE_URL,
  },
});



